#!/bin/sh
. "$(dirname "$0")/husky.sh"

echo "Lint-staged command start..."

npx lint-staged

echo "Starting Cypress tests..."
npx cypress run

if [ $? -ne 0 ]; then
  echo "Cypress tests failed. Please fix the errors before committing."
  exit 1
fi